### ISSUE TITLE
create templates (breadth, depth, login)

### ISSUE THREAD

**Issue by jaerikson** [L4LabUA/scivocab#11]
right now we have one (index.html). we need at least 3 separate templates:
- breadth task
- depth task
- login page

**Comment by jaerikson** [comment]
Sam and Adarsh were creating additional templates... @adarshp what do we have now?

**Comment by adarshp** [comment]
We have those three + a template for when the breadth tasks is successfully completed (after.py): https://github.com/L4LabUA/scivocab/tree/master/templates
