### ISSUE TITLE
add audio for each target word

### ISSUE THREAD

**Issue by jaerikson** [L4LabUA/scivocab#13]
e.g., "arachnid" will play for b001

ideally I'd like audio to play
- automatically for each page/task item
- when the child clicks a button (optional replay of audio recording as needed)

**Comment by jaerikson** [comment]
@schoelen this isn't quite ready yet but assigning this to you for when the audio is ready :)

**Comment by adarshp** [comment]
@alyhlndr1233 To align the audio file with the word being displayed, replace `"scivocab/audio/w001_ara.wav"` with `"scivocab/audio/"+current_word.id.replace('b','w')+"_"+current_word.tw[0:3]` here: https://github.com/L4LabUA/scivocab/blob/c402587f9b3b5672b2f22a6461795cab832c3756/app/templates/breadth.html#L53.

**Explanation**: `current_word` is a variable that represents the current word being shown. The type of this variable is `Word`. The template for creating variables of this type is defined here: https://github.com/L4LabUA/scivocab/blob/master/app/word.py.

If you look at these lines: https://github.com/L4LabUA/scivocab/blob/36c71ba36717c3da1c9d8d7c36c5c46fe1b4e370/app/word.py#L7-L18 you'll see that `Word` objects have a few different properties. The `id` property on line 18 is what we are interested in. The replacement I suggested above takes the `id` (which is equal to the value of the `breadth_id` column in this file: https://github.com/L4LabUA/scivocab/blob/master/app/static/scivocab/audio.csv and is associated with the word by the `construct_word_dict` function in this file: https://github.com/L4LabUA/scivocab/blob/master/app/translate.py), replaces the letter `b` with the letter `w`, then appends an underscore followed by the first three letters of the 'true word' which is stored in the `tw` property of `current_word`.

The `tw` property corresponds to the `target` column of this file: https://github.com/L4LabUA/scivocab/blob/master/app/static/scivocab/sv_bv1_input.csv, which is loaded by the webapp on this line: https://github.com/L4LabUA/scivocab/blob/36c71ba36717c3da1c9d8d7c36c5c46fe1b4e370/app/breadth.py#L35

**Comment by adarshp** [comment]
@alyhlndr1233 These instructions will no longer work with the updates I made to the code over the winter break, so don't worry about this task for now.

**Comment by adarshp** [comment]
Closed by #33 .
